### ISSUE TITLE
Deploy with Netlify

### ISSUE THREAD

**Issue by aquibbaig** [aquibbaig/club-website#3]
Travis CI is used for continuous deployment of websites, without any error/hassle.
Check this for implementation `https://www.linode.com/docs/websites/static-sites/install-gatsbyjs/`

**Comment by aquibbaig** [comment]
@ankitjena is working on it!

**Comment by aquibbaig** [comment]
We thought that we will drop the idea of CI or writing unit tests for a small scale static site generator like our website.

**Comment by ankitjena** [comment]
Deploying with netlify seems a better option as better support is provided. Also @aquibbaig since you are the owner of the repo you should set it up.

**Comment by aquibbaig** [comment]
Working on it!

**Comment by aquibbaig** [comment]
Deployed to Netlify: `https://nostalgic-clarke-b9335d.netlify.com/`
